[package]
name = "asyncho"
version = "0.1.0"
authors = ["Trent Clarke <tcc@planetinnovation.com.au>"]

[dependencies]
bytes="*"
env_logger = "0.4.2"
futures = "0.1.9"
log = "0.3.7"
tokio-core="0.1.6"
tokio-io="*"
